In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
#array operations
#brodcasting
arr = np.array([1,2,3,4])
arr+5

array([6, 7, 8, 9])

In [13]:
#deep and sallow copy 
#shallow copy is does changes in both arrays if one is changed
#deep copy is independent
#matrix opertions
ma1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
ma1
ma2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
ma2
ma1@ma2 # matrix multiplication = ma1.dot(ma2)


array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [15]:
ma1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [16]:
#array manipulation
arr_a = np.array([1,2 ,3])
arr_b = np.array([4,5,6])

In [22]:
np.vstack((arr_a,arr_b))
np.column_stack((arr_a,arr_b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]