In [ ]:
import numpy as np



In [5]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [6]:
list_data = [[3, 4, 6],[5, 7, 8]]
array_2d = np.array(list_data)
print(array_2d)

[[3 4 6]
 [5 7 8]]


In [7]:
series = np.arange(0, 10, 2)
print(series)

[0 2 4 6 8]


In [12]:
arr = np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
arr = np.ones((4,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
#linear_spacing
lin_space = np.linspace(0,1,10)
print(lin_space)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [82]:
#random numbers libary and array
# np.random.rand(5)
np.random.randn(10)

array([-0.88929925,  1.11283141,  2.26325772,  0.44397707,  1.24285377,
       -0.05602248, -0.43878132, -0.14365484, -0.80792055,  0.35689821])

In [128]:
np.random.randint(10,20)

13

In [130]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [132]:
arr.shape

(3, 3)

In [134]:
arr.size

9

In [135]:
arr.dtype

dtype('int64')

In [139]:
arr.min()

np.int64(1)

In [141]:
arr.max()

np.int64(9)

In [146]:
np.sum(arr, axis=0)  #column wise sum axis = 0 

array([12, 15, 18])

In [149]:
arr.argmax()

np.int64(8)

In [150]:
arr.argmin()

np.int64(0)

In [154]:
#reshaping and resizing
arr = np.arange(1,31)

In [155]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])