In [1]:
import numpy as np

In [8]:
arr = np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [13]:
#slicing in array in numpy
arr[3::2]

array([14, 16, 18, 20])

In [18]:
#numpy indexing and slicing
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [25]:
arr[5,4] 

np.int64(30)

In [27]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [29]:
#boolean indexing
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
bool_index = arr % 2 == 0
arr = arr[bool_index]